version: '3'
services:
  app:
    container_name: ${APP_NAME}
    build:
      context: .
      args:
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${BUNDLE_RUBYGEMS__PKG__GITHUB__COM}
    stdin_open: true
    tty: true
    profiles: [ "server" ]
    environment:
      #      DB_USER: fastag_service
      #      DB_PASSWORD: fastag_service
      #      DB_HOSTNAME: db
      #      DB_NAME: ${DB_NAME}
      RAILS_ENV: ${RAILS_ENV}
      DD_AGENT_HOST: apm
#      DD_TRACE_AGENT_PORT: 8126