version: '3'
services:
  app:
    container_name: ${APP_NAME}
    build:
      context: .
      args:
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${BUNDLE_RUBYGEMS__PKG__GITHUB__COM}
    stdin_open: true
    tty: true
    profiles: [ "server" ]
    environment:
      RUNNING_ON_K8S: true
      RAILS_ENV: staging
      PASSENGER_APP_ENV: staging
      CONFIGURATION_SERVER_ENABLED: true
      APPLICATION: loconav-developer-apis
      POD: staging13
      RAILS_LOG_TO_STDOUT: true
      CLIENT: 330e0848-b9d0-4784-a620-1e73fd700c20
      SECRET: InAzXwB0JFXSqABKi33Y5RL6Ec44UIYc
      DISABLE_SIDEKIQ_ALIVE: false
      LINEHAUL_BASE_URL: https://linehaul.stg13.loconav.dev
      SECRET_KEY_BASE: f56bda0d462bb01772428cba97bd1abdd9fbad323d1f2
      FULL_LOG_ENABLED: true
      FULL_LOG_EXCLUDE_API_PATHS:
      FULL_LOG_HEADERS: User-Authentication
      FULL_LOG_INCLUDE_API_PATHS: /api/
      FULL_LOG_RESOURCE_TYPE: api
      FULL_LOG_SOURCE: loconav-developer-apis
      HEADER_USER_AUTHENTICATION: User-Authentication
      REDIS_HOST: marketplace-redis-lc
      LOCONAV_DEVELOPER_APIS_PG_NAME: lcnv_dev_apis_db
      LOCONAV_DEVELOPER_APIS_PG_HOST: lcnv-dev-apis-db-lc
      LOCONAV_DEVELOPER_APIS_PG_USERNAME: lcnv_dev_apis
      LOCONAV_DEVELOPER_APIS_PG_PASSWORD: 93tBzXq3e4
      LOCONAV_VIDEO_TELEMATICS_URL: vt-web.stg13.loconav.dev
      #      DB_USER: fastag_service
      #      DB_PASSWORD: fastag_service
      #      DB_HOSTNAME: db
      #      DB_NAME: ${DB_NAME}
      DD_AGENT_HOST: apm
#      DD_TRACE_AGENT_PORT: 8126