version: '3'
services:
  app:
    container_name: ${APP_NAME}
    build:
      context: .
      args:
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${BUNDLE_RUBYGEMS__PKG__GITHUB__COM}
    stdin_open: true
    tty: true
    profiles: [ "server" ]
    environment:
      RUNNING_ON_K8S: ${RUNNING_ON_K8S}
      RAILS_ENV: ${RAILS_ENV}
      PASSENGER_APP_ENV: ${PASSENGER_APP_ENV}
      CONFIGURATION_SERVER_ENABLED: ${CONFIGURATION_SERVER_ENABLED}
      APPLICATION: ${APPLICATION}
      POD: ${POD}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT}
      CLIENT: ${CLIENT}
      SECRET: ${SECRET}
      DISABLE_SIDEKIQ_ALIVE: ${DISABLE_SIDEKIQ_ALIVE}
      LINEHAUL_BASE_URL: ${LINEHAUL_BASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      FULL_LOG_ENABLED: ${FULL_LOG_ENABLED}
      FULL_LOG_EXCLUDE_API_PATHS: ${FULL_LOG_EXCLUDE_API_PATHS}
      FULL_LOG_HEADERS: ${FULL_LOG_HEADERS}
      FULL_LOG_INCLUDE_API_PATHS: ${FULL_LOG_INCLUDE_API_PATHS}
      FULL_LOG_RESOURCE_TYPE: ${FULL_LOG_RESOURCE_TYPE}
      FULL_LOG_SOURCE: ${FULL_LOG_SOURCE}
      HEADER_USER_AUTHENTICATION: ${HEADER_USER_AUTHENTICATION}
      REDIS_HOST: ${REDIS_HOST}
      LOCONAV_DEVELOPER_APIS_PG_NAME: ${LOCONAV_DEVELOPER_APIS_PG_NAME}
      LOCONAV_DEVELOPER_APIS_PG_HOST: ${LOCONAV_DEVELOPER_APIS_PG_HOST}
      LOCONAV_DEVELOPER_APIS_PG_USERNAME: ${LOCONAV_DEVELOPER_APIS_PG_USERNAME}
      LOCONAV_DEVELOPER_APIS_PG_PASSWORD: ${LOCONAV_DEVELOPER_APIS_PG_PASSWORD}
      LOCONAV_VIDEO_TELEMATICS_URL: ${LOCONAV_VIDEO_TELEMATICS_URL}
      DD_AGENT_HOST: apm