---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/drivers":
    get:
      summary: list drivers
      parameters:
        - in: query
          name: name
          type: string
          required: false
      responses:
        '200':
          description: successful
  "/api/v1/vehicle/telematics/last_known":
    post:
      summary: last_known vehicle_stat
      responses:
        '200':
          description: successful
servers:
- url: localhost:3000
  variables:
    defaultHost:
      default: www.example.com
