default:
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  pool: 5
  database: loconav_developer_apis
  username: loconav
  password: loconav
  host: lcnv-dev-apis-db-lc
  port: 5432
  variables:
    statement_timeout: 10000

