default: &default
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  pool: 5
  database: loconav_developer_apis
  username:
  password:
  host: localhost
  port: 5432
  variables:
    statement_timeout: 10000

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

pre-prod:
  <<: *default
