common: &common_settings
  linehaul_base_url: <%= ENV.fetch("LINEHAUL_BASE_URL") %>


FULL_LOG: &full_log
  full_log_resource_type: <%= ENV.fetch("FULL_LOG_RESOURCE_TYPE")  %>
  full_log_source: <%= ENV.fetch("FULL_LOG_SOURCE") %>
  full_log_headers: <%= ENV.fetch("FULL_LOG_HEADERS") %>
  full_log_include_api_paths: <%= ENV.fetch("FULL_LOG_INCLUDE_API_PATHS") %>
  full_log_exclude_api_paths: <%= ENV.fetch("FULL_LOG_EXCLUDE_API_PATHS") %>


development:
  <<: *common_settings
  <<: *full_log

test:
  <<: *common_settings

production:
  <<: *common_settings

staging:
  <<: *common_settings
  <<: *full_log

preprod:
  <<: *common_settings
