
common: &common_settings
  linehaul_base_url: https://linehaul.stg13.loconav.dev
  header_user_authentication: User-Authentication

development:
  <<: *common_settings

test:
  <<: *common_settings

production:
  <<: *common_settings

staging:
  <<: *common_settings

preprod:
  <<: *common_settings
