
common: &common_settings
  linehaul_base_url: <%= ENV.fetch("LINEHAUL_BASE_URL") %>
  header_user_authentication: <%= ENV.fetch("HEADER_USER_AUTHENTICATION") %>

development:
  <<: *common_settings

test:
  <<: *common_settings

production:
  <<: *common_settings

staging:
  <<: *common_settings

preprod:
  <<: *common_settings
