
common: &common_settings
  linehaul_base_url: <%= ENV.fetch("LINEHAUL_BASE_URL") %>

development:
  <<: *common_settings

test:
  <<: *common_settings

production:
  <<: *common_settings

staging:
  <<: *common_settings

preprod:
  <<: *common_settings
