history_supported_sensors:
  ac: engine_sensor
  acceleration_pedal_position: engine_sensor
  adblu_level: engine_sensor
  ambient_air_temperature: engine_sensor
  auto_retarder_switch: engine_sensor
  axle_weight: engine_sensor
  back_cap_lock: engine_sensor
  battery_charge_state: engine_sensor
  battery_level: engine_sensor
  ble_battery: engine_sensor
  ble_humidity: engine_sensor
  bms_battery_current: engine_sensor
  bms_battery_voltage: engine_sensor
  bms_charge_capacity: engine_sensor
  bms_charge_cycle_number: engine_sensor
  bms_charging: engine_sensor
  bms_charging_current: engine_sensor
  bms_discharging_current: engine_sensor
  bms_soc: engine_sensor
  bms_terminal_voltage: engine_sensor
  calculated_engine_load_value: engine_sensor
  can_odometer_value: engine_sensor
  clutch_pedal: engine_sensor
  cruise_control: engine_sensor
  device_battery: engine_sensor
  distance_mil_on: engine_sensor
  distance_travelled_since_code_cleared: engine_sensor
  door: engine_sensor
  elock: engine_sensor
  engine_coolant_temperature: engine_sensor
  engine_intake_manifold_1_temperature: engine_sensor
  engine_oil_temperature: engine_sensor
  engine_rpm: engine_sensor
  engine_temperature: engine_sensor
  engine_total_fuel_used: engine_sensor
  engine_working: engine_sensor
  front_left_door: engine_sensor
  front_right_door: engine_sensor
  fuel: engine_sensor
  fuel_consumption: engine_sensor
  fuel_obd: engine_sensor
  fuel_tank_level: engine_sensor
  gsm_strength: engine_sensor
  hood_door: engine_sensor
  ignition: engine_sensor
  intake_manifold_absolute_pressure: engine_sensor
  lock_cut_status: engine_sensor
  long_time_unlocking: engine_sensor
  max_air_flow_rate: engine_sensor
  motor_stuck: engine_sensor
  movement: engine_sensor
  parking_brake: engine_sensor
  plugged: engine_sensor
  power_cut_status: engine_sensor
  rear_left_door: engine_sensor
  rear_right_door: engine_sensor
  relay: engine_sensor
  retarder_state: engine_sensor
  runtime_engine_start: engine_sensor
  seat_belt: engine_sensor
  sos: engine_sensor
  speed: engine_sensor
  Temperature: engine_sensor
  total_mileage: engine_sensor
  trip_button: engine_sensor
  trunk_door: engine_sensor
  unauthorized_rfid: engine_sensor
  vehicle_battery: engine_sensor
  wrong_lock_password: engine_sensor