sensor_types:
  gps: GpsSensor
  power_cut_status_value: EngineSensor
  temperature_value: EngineSensor
  ignition_value: EngineSensor
  orientation_value: EngineSensor
  battery_level_value: EngineSensor