sensor_types:
  ambient_temperature_value:
    sensor_klass: EngineSensor
    metric_type: metric
  battery_level_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: device_battery_metric
  battery_temperature: EngineSensor
    sensor_klass: EngineSensor
    metric_type: ev_metric
  device_temperature: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  engine_coolant_temperature_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  engine_fuel_rate_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  engine_fuel_temperature: EngineSensor
  engine_intake_manifold_1_temperature_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  engine_oil_temperature_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  engine_operation_status: EngineSensor
  engine_rpm_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  engine_temperature_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  engine_working_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  fuel_consumption_counted: EngineSensor
    sensor_klass: EngineSensor
    metric_type: sensor_metric
  fuel_consumption_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  fuel_injection_quantity: EngineSensor
  fuel_level_2_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  fuel_level_obd_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  fuel_quantity: EngineSensor
  fuel_rail_pressure: EngineSensor
  fuel_rate_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  fuel_tank_level_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  fuel_temperature: EngineSensor
  fuel_trim: EngineSensor
  fuel_type: EngineSensor
  fuel_used_high_resolution_value: EngineSensor
  fuel_used_value: EngineSensor
  fuel_value: EngineSensor
  gps: GpsSensor
  ignition_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: sensor_metric
  imsi: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  internal_storage_used: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  internal_storage_size: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  last_ignition_on_time:
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  orientation_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: sensor_metric
  power_cut_status_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: metric
  rssi: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  sd_card_cid: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  sd_card_status: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  sd_card_storage_size: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  sd_card_storage_used: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  sim_card_status: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  temperature_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  washer_fluid_level_value: EngineSensor
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  lac:
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  mcc:
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  mnc:
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  cell_id:
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  serial_number:
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  app_version:
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  update_version:
    sensor_klass: EngineSensor
    metric_type: vt_sensors
  device_firmware_version:
    sensor_klass: EngineSensor
    metric_type: vt_sensors