sensor_types:
  gps: gps
  current_location_coordinates: gps
  current_location_value: current_location_value
  ignition: gps
  digital_input_1: digital_input
  digital_input_2: digital_input
  digital_input_3: digital_input
  digital_input_4: digital_input
  cruise_control: cruise_control
  parking_brake: parking_brake
  retarder_state: retarder_state
  power_cut_status: power_cut_status
  movement: movement
  auto_retarder_switch: auto_retarder_switch
  clutch_pedal: clutch_pedal
  engine_working: engine_working
  digital_output_1: digital_output
  bms_discharge_over_current: bms_discharge_over_current
  bms_charge_over_current: bms_charge_over_current
  bms_short_circuit: bms_short_circuit
  bms_cell_under_voltage: bms_cell_under_voltage
  bms_cell_over_voltage: bms_cell_over_voltage
  bms_cell_under_temperature: bms_cell_under_temperature
  bms_cell_over_temperature: bms_cell_over_temperature
  bms_system_error: bms_system_error
  seat_belt: seat_belt
  front_left_door: front_left_door
  front_right_door: front_right_door
  rear_left_door: rear_left_door
  rear_right_door: rear_right_door
  hood_door: hood_door
  trunk_door: trunk_door
  driver_door: driver_door
  sd_card_status: sd_card_status
  bms_charging: bms_charging
  vehicle_battery_level: vehicle_battery_level
  fuel_1: fuel
  fuel_2: fuel
  fuel_3: fuel
  fuel_4: fuel
  fuel_5: fuel
  temperature_1: temperature
  temperature_2: temperature
  temperature_3: temperature
  temperature_4: temperature
  device_battery_level: device_battery_level
  temperature_5: temperature
  temperature_6: temperature
  temperature_7: temperature
  temperature_8: temperature
  gsm_strength: gsm_strength
  fuel_level_in_litre: fuel_level_in_litre
  calculated_engine_load_value: calculated_engine_load_value
  runtime_engine_start: runtime_engine_start
  battery_level: battery_level
  can_odometer_value: can_odometer_value
  acceleration_pedal_position: acceleration_pedal_position
  engine_temperature: engine_temperature
  engine_total_fuel_used: engine_total_fuel_used
  fuel_consumption: fuel_consumption
  fuel_tank_level: fuel_tank_level
  adblu_level: adblu_level
  ambient_air_temperature: ambient_air_temperature
  distance_mil_on: distance_mil_on
  distance_travelled_since_code_cleared: distance_travelled_since_code_cleared
  engine_coolant_temperature: engine_coolant_temperature
  engine_rpm: engine_rpm
  engine_intake_manifold_1_temperature: engine_intake_manifold_1_temperature
  total_mileage: total_mileage
  axle_weight: axle_weight
  bms_battery_voltage: bms_battery_voltage
  bms_battery_current: bms_battery_current
  bms_soc: bms_soc
  bms_charge_cycle_number: bms_charge_cycle_number
  bms_terminal_voltage: bms_terminal_voltage
  bms_charging_current: bms_charging_current
  bms_discharging_current: bms_discharging_current
  bms_charge_capacity: bms_charge_capacity
  battery_charge_state: battery_charge_state
  engine_oil_temperature: engine_oil_temperature
  lls_temperature_1: lls_temperature
  lls_temperature_2: lls_temperature
  bms_cell_temperature_1: bms_cell_temperature
  bms_cell_temperature_2: bms_cell_temperature
  bms_cell_temperature_3: bms_cell_temperature
  bms_cell_temperature_4: bms_cell_temperature
  bms_cell_temperature_5: bms_cell_temperature
  bms_cell_temperature_6: bms_cell_temperature
  bms_cell_temperature_7: bms_cell_temperature
  bms_cell_temperature_8: bms_cell_temperature
  bms_cell_temperature_9: bms_cell_temperature
  bms_cell_temperature_10: bms_cell_temperature
  bms_cell_temperature_11: bms_cell_temperature
  bms_cell_temperature_12: bms_cell_temperature
  bms_cell_temperature_13: bms_cell_temperature
  bms_cell_temperature_14: bms_cell_temperature
  bms_cell_temperature_15: bms_cell_temperature
  bms_cell_temperature_16: bms_cell_temperature
  bms_ntc_temperature_1: bms_ntc_temperature
  bms_ntc_temperature_2: bms_ntc_temperature
  bms_ntc_temperature_3: bms_ntc_temperature
  bms_ntc_temperature_4: bms_ntc_temperature
  bms_ntc_temperature_5: bms_ntc_temperature
  bms_ntc_temperature_6: bms_ntc_temperature
  battery_temperature: battery_temperature
  speed: gps
  control_module_voltage: control_module_voltage
  engine_fuel_rate: engine_fuel_rate
  fuel_level: fuel_level
  throttle_position: throttle_position
  number_of_satellites: number_of_satellites
  accelerator_pedal_position: accelerator_pedal_position
  accelerator_pedal_position_1: accelerator_pedal_position
  wheelbased_vehicle_speed: wheelbased_vehicle_speed
  engine_oil_level: engine_oil_level
  orientation: gps
  altitude: altitude
  odometer: odometer
  hdop: hdop
  brake_pedal_switch: brake_pedal_switch
  retarder_manual: retarder_manual
  bluetooth_humidity_1: bluetooth_humidity
  bluetooth_battery_1: bluetooth_battery
  vehicle_voltage: vehicle_voltage
  wifi_mac_addresses: wifi_mac_addresses
  wifi_strength: wifi_strength
  axle_load_1: axle_load
  axle_load_2: axle_load
  axle_load_3: axle_load
  axle_load_4: axle_load
  axle_load_5: axle_load
  fuel_consumption_counted: fuel_consumption_counted
  control_state_flag: control_state_flag
  control_state_flag_p4: control_state_flag_p4
  driver_seat_belt: driver_seat_belt
  front_passenger_seat_belt: front_passenger_seat_belt
  rear_left_seat_belt: rear_left_seat_belt
  rear_right_seat_belt: rear_right_seat_belt
  rear_centre_seat_belt: rear_centre_seat_belt
  immobilization_status: immobilization_status
  power_take_off: power_take_off
  sd_card_storage_size: sd_card_storage_size
  sd_card_storage_used: sd_card_storage_used
  sd_card_cid: sd_card_cid
  internal_storage_size: internal_storage_size
  internal_storage_used: internal_storage_used
  sim_card_status: sim_card_status
  device_temperature: device_temperature
  rssi: rssi
  imsi: imsi
  last_ignition_on_time: last_ignition_on_time
  lac: lac
  mcc: mcc
  mnc: mnc
  cell_id: cell_id
  serial_number: serial_number
  app_version: app_version
  update_version: update_version
  device_firmware_version: device_firmware_version
  ibutton: ibutton
  bms_cell_voltage_1: bms_cell_voltage
  bms_cell_voltage_10: bms_cell_voltage
  bms_cell_voltage_11: bms_cell_voltage
  bms_cell_voltage_12: bms_cell_voltage
  bms_cell_voltage_13: bms_cell_voltage
  bms_cell_voltage_14: bms_cell_voltage
  bms_cell_voltage_15: bms_cell_voltage
  bms_cell_voltage_16: bms_cell_voltage
  bms_cell_voltage_2: bms_cell_voltage
  bms_cell_voltage_3: bms_cell_voltage
  bms_cell_voltage_4: bms_cell_voltage
  bms_cell_voltage_5: bms_cell_voltage
  bms_cell_voltage_6: bms_cell_voltage
  bms_cell_voltage_7: bms_cell_voltage
  bms_cell_voltage_8: bms_cell_voltage
  bms_cell_voltage_9: bms_cell_voltage
  bms_charge_discharge_status: bms_charge_discharge_status
  bms_current: bms_current
  bms_distance_travelled_all: bms_distance_travelled_all
  bms_distance_travelled_today: bms_distance_travelled_today
  bms_maximum_cell_voltage_number: bms_maximum_cell_voltage_number
  bms_maximum_cell_voltage_value: bms_maximum_cell_voltage_value
  bms_minimum_cell_voltage_number: bms_minimum_cell_voltage_number
  bms_minimum_cell_voltage_value: bms_minimum_cell_voltage_value
  bms_voltage: bms_voltage
  absolute_fuel_rail_pressure: absolute_fuel_rail_pressure
  direct_fuel_rail_pressure: direct_fuel_rail_pressure
  engine_on_time: engine_on_time
  fuel_rate: fuel_rate
  mil_status: mil_status
  sensed_battery_volatge: sensed_battery_volatge
  driver_propulsion_torque: driver_propulsion_torque
  t50_status: t50_status
  egr_pos_sensor_voltage: egr_pos_sensor_voltage
  charged_air_cooler_temp: charged_air_cooler_temp
  particle_filter_pressure: particle_filter_pressure
  pwm_signal_output: pwm_signal_output
  engine_operation_status: engine_operation_status
  engine_starting_issue_svc: engine_starting_issue_svc
  boost_pressure: boost_pressure
  ambient_pressure: ambient_pressure
  rail_pressure_set_point: rail_pressure_set_point
  fuel_injection_quantity: fuel_injection_quantity
  max_fuel_quantity: max_fuel_quantity
  prv_open_duration: prv_open_duration
  t15_status: t15_status
  svs_lamp_status: svs_lamp_status
  torque_generating_efi: torque_generating_efi
  engine_fuel_temperature: engine_fuel_temperature
  bluetooth_humidity_2: bluetooth_humidity
  bluetooth_humidity_3: bluetooth_humidity
  bluetooth_humidity_4: bluetooth_humidity
  bms_residual_capacity: bms_residual_capacity
  bms_discharge_cycles: bms_discharge_cycles
  bms_full_capacity: bms_full_capacity
  bms_equilibrium_state: bms_equilibrium_state
  bms_equilibrium_status: bms_equilibrium_status
  bms_protection_marks: bms_protection_marks
  bms_software_version: bms_software_version
  bms_production_date: bms_production_date
  bms_status_symbol: bms_status_symbol
  bms_battery_strings: bms_battery_strings
  bms_ntc_probes: bms_ntc_probes
  bms_cell_voltage_17: bms_cell_voltage
  bms_cell_voltage_18: bms_cell_voltage
  bms_cell_voltage_19: bms_cell_voltage
  bms_cell_voltage_20: bms_cell_voltage
  bms_cell_voltage_21: bms_cell_voltage
  bms_cell_voltage_22: bms_cell_voltage
  bms_cell_voltage_23: bms_cell_voltage
  bms_cell_voltage_24: bms_cell_voltage
  bms_cell_voltage_25: bms_cell_voltage
  bms_cell_voltage_26: bms_cell_voltage
  bms_cell_voltage_27: bms_cell_voltage
  bms_cell_voltage_28: bms_cell_voltage
  bms_cell_voltage_29: bms_cell_voltage
  bms_cell_voltage_30: bms_cell_voltage
  bms_discharge_mos_switch_control: bms_discharge_mos_switch_control
  bms_discharge_switch_control_backcode: bms_discharge_switch_control_backcode
  bms_charging_mos_switch_control: bms_charging_mos_switch_control
  bms_charging_switch_control_reverse_code: bms_charging_switch_control_reverse_code
  bms_equilibrium_state_1: bms_equilibrium_state
  bms_equilibrium_state_2: bms_equilibrium_state
  bms_equilibrium_state_3: bms_equilibrium_state
  bms_equilibrium_state_4: bms_equilibrium_state
  bms_equilibrium_state_5: bms_equilibrium_state
  bms_equilibrium_state_6: bms_equilibrium_state
  bms_equilibrium_state_7: bms_equilibrium_state
  bms_equilibrium_state_8: bms_equilibrium_state
  bms_equilibrium_state_9: bms_equilibrium_state
  bms_equilibrium_state_10: bms_equilibrium_state
  bms_equilibrium_state_11: bms_equilibrium_state
  bms_equilibrium_state_12: bms_equilibrium_state
  bms_equilibrium_state_13: bms_equilibrium_state
  bms_equilibrium_state_14: bms_equilibrium_state
  bms_equilibrium_state_15: bms_equilibrium_state
  bms_equilibrium_state_16: bms_equilibrium_state
  bms_equilibrium_status_17: bms_equilibrium_status
  bms_equilibrium_status_18: bms_equilibrium_status
  bms_equilibrium_status_19: bms_equilibrium_status
  bms_equilibrium_status_20: bms_equilibrium_status
  bms_equilibrium_status_21: bms_equilibrium_status
  bms_equilibrium_status_22: bms_equilibrium_status
  bms_equilibrium_status_23: bms_equilibrium_status
  bms_equilibrium_status_24: bms_equilibrium_status
  bms_equilibrium_status_25: bms_equilibrium_status
  bms_equilibrium_status_26: bms_equilibrium_status
  bms_equilibrium_status_27: bms_equilibrium_status
  bms_equilibrium_status_28: bms_equilibrium_status
  bms_equilibrium_status_29: bms_equilibrium_status
  bms_equilibrium_status_30: bms_equilibrium_status
  bms_equilibrium_status_31: bms_equilibrium_status
  bms_equilibrium_status_32: bms_equilibrium_status
  num_dtc_codes: num_dtc_codes
  short_fuel_trim: short_fuel_trim
  intake_map: intake_map
  timing_advance: timing_advance
  intake_air_temperature: intake_air_temperature
  barometric_pressure: barometric_pressure
  absolute_load_value: absolute_load_value
  fuel_type: fuel_type
  fast_charging: fast_charging
  time_to_full_charge_minutes: time_to_full_charge_minutes
  can_speed: can_speed
  engine_running_hours: engine_running_hours
  tell_tale_0: tell_tale_0
  pto_rpm: pto_rpm
  bms_maximum_cell_temperature_value: bms_maximum_cell_temperature_value
  bms_maximum_cell_temperature_number: bms_maximum_cell_temperature_number
  bms_minimum_cell_temperature_value: bms_minimum_cell_temperature_value
  bms_minimum_cell_temperature_number: bms_minimum_cell_temperature_number
  bms_charging_mos_tube_status: bms_charging_mos_tube_status
  bms_discharging_mos_tube_status: bms_discharging_mos_tube_status
  bms_life: bms_life
  bms_number_of_temperature: bms_number_of_temperature
  bms_charger_status: bms_charger_status
  bms_load_status: bms_load_status
  bms_charge_discharge_cycles: bms_charge_discharge_cycles
  bms_voltage_frame_number_1: bms_voltage_frame_number
  bms_voltage_frame_number_2: bms_voltage_frame_number
  bms_voltage_frame_number_3: bms_voltage_frame_number
  bms_voltage_frame_number_4: bms_voltage_frame_number
  bms_voltage_frame_number_5: bms_voltage_frame_number
  bms_voltage_frame_number_6: bms_voltage_frame_number
  bms_temperature_frame_number_1: bms_temperature_frame_number
  bms_dischg_temp_high_level_1: bms_dischg_temp_high_level
  bms_dischg_temp_high_level_2: bms_dischg_temp_high_level
  bms_dischg_temp_low_level_1: bms_dischg_temp_low_level
  bms_dischg_temp_low_level_2: bms_dischg_temp_low_level
  bms_chg_overcurrent_level_1: bms_chg_overcurrent_level
  bms_chg_overcurrent_level_2: bms_chg_overcurrent_level
  bms_dischg_overcurrent_level_1: bms_dischg_overcurrent_level
  bms_dischg_overcurrent_level_2: bms_dischg_overcurrent_level
  bms_soc_high_level_1: bms_soc_high_level
  bms_soc_high_level_2: bms_soc_high_level
  bms_soc_low_level_1: bms_soc_low_level
  bms_soc_low_level_2: bms_soc_low_level
  bms_diff_volt_level_1: bms_diff_volt_level
  bms_diff_volt_level_2: bms_diff_volt_level
  bms_diff_temp_level_1: bms_diff_temp_level
  bms_diff_temp_level_2: bms_diff_temp_level
  bms_cell_volt_high_level_1: bms_cell_volt_high_level
  bms_cell_volt_high_level_2: bms_cell_volt_high_level
  bms_cell_volt_low_level_1: bms_cell_volt_low_level
  bms_cell_volt_low_level_2: bms_cell_volt_low_level
  bms_sum_volt_high_level_1: bms_sum_volt_high_level
  bms_sum_volt_high_level_2: bms_sum_volt_high_level
  bms_sum_volt_low_level_1: bms_sum_volt_low_level
  bms_sum_volt_low_level_2: bms_sum_volt_low_level
  bms_chg_temp_high_level_1: bms_chg_temp_high_level
  bms_chg_temp_high_level_2: bms_chg_temp_high_level
  bms_chg_temp_low_level_1: bms_chg_temp_low_level
  bms_chg_temp_low_level_2: bms_chg_temp_low_level
  spare_1: spare
  spare_2: spare
  spare_3: spare
  spare_4: spare
  spare_5: spare
  spare_6: spare
  spare_7: spare
  spare_8: spare
  spare_9: spare
  spare_10: spare
  spare_11: spare
  spare_12: spare
  spare_13: spare
  injection_time_1: injection_time
  injection_time_2: injection_time
  desired_pol_1_injection_quantity_1: desired_pol_1_injection_quantity
  desired_pol_1_injection_quantity_2: desired_pol_1_injection_quantity
  desired_pol_2_injection_quantity_1: desired_pol_2_injection_quantity
  desired_pol_2_injection_quantity_2: desired_pol_2_injection_quantity
  prv_open_count: prv_open_count
  throttle_valve_actuator_position: throttle_valve_actuator_position
  egr_position: egr_position
  engine_oil_pressure: engine_oil_pressure
  data_upload_size_in_kb: data_upload_size_in_kb
  data_download_size_in_kb: data_download_size_in_kb
  engine_oil_temperature_in_mv: engine_oil_temperature_in_mv
  engine_oil_pressure_in_mv: engine_oil_pressure_in_mv
  distance_to_empty_km: distance_to_empty_km
  fuel_tank: fuel_tank
  trailer: trailer
  device_battery: device_battery
  vehicle_battery: vehicle_battery
  sos: sos
  ev_sports_mode_status: ev_sports_mode_status
  ev_dte: ev_dte
  engine_intake_manifold_temperature: engine_intake_manifold_temperature
  rock_breaker_pedal_value: rock_breaker_pedal_value
  sig_key_on_indicator: sig_key_on_indicator
  total_distance_high_resolution: total_distance_high_resolution
  washer_fluid_level: washer_fluid_level
  engine_percentage_torque: engine_percentage_torque
  engine_hours: engine_hours
  bms_cell_voltage: bms_cell_voltage
  bms_ntc_temperature: bms_ntc_temperature
  bms_number_of_battery_string: bms_number_of_battery_string
  bms_voltage_frame_number: bms_voltage_frame_number
  bms_temperature_frame_number: bms_temperature_frame_number
  bms_cell_volt_high_level: bms_cell_volt_high_level
  bms_sum_volt_high_level: bms_sum_volt_high_level
  bms_sum_volt_low_level: bms_sum_volt_low_level
  bms_dischg_temp_high_level: bms_dischg_temp_high_level
  bms_soc_low_level: bms_soc_low_level
  back_cap_lock: back_cap_lock
  rotation_direction: rotation_direction
  bms_diff_temp_level: bms_diff_temp_level
  unauthorized_rfid: unauthorized_rfid
  desired_pol_1_injection_quantity: desired_pol_1_injection_quantity
  rotation_speed: rotation_speed
  spare: spare
  injection_time: injection_time
  rail_pressure: rail_pressure
  bms_dischg_temp_low_level: bms_dischg_temp_low_level
  injection_quantity_set_point: injection_quantity_set_point
  bms_cell_temperature: bms_cell_temperature
  bms_chg_overcurrent_level: bms_chg_overcurrent_level
  bms_cell_volt_low_level: bms_cell_volt_low_level
  long_time_unlocking: long_time_unlocking
  rail_pressure_setpoint: rail_pressure_setpoint
  desired_pol_2_injection_quantity: desired_pol_2_injection_quantity
  lock_cut_status: lock_cut_status
  bms_diff_volt_level: bms_diff_volt_level
  wrong_lock_password: wrong_lock_password
  sensed_battery_voltage: sensed_battery_voltage
  bms_dischg_overcurrent_level: bms_dischg_overcurrent_level
  rotation_count: rotation_count
  bms_chg_temp_high_level: bms_chg_temp_high_level
  bms_chg_temp_low_level: bms_chg_temp_low_level
  max_air_flow_rate: max_air_flow_rate
  intake_manifold_absolute_pressure: intake_manifold_absolute_pressure
  bms_soc_high_level: bms_soc_high_level
  door: door
  ac: ac
  drum: drum
  trip_button: trip_button
  compressor: compressor
  plugged: plugged
  relay: relay
  motor_stuck: motor_stuck
  elock: elock
  fuel: fuel
  temperature: temperature
  ble_humidity: ble_humidity
  ble_battery: ble_battery