apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
spec:
  template:
    spec:
    {{ if .Values.job.imagePullSecrets }}
      imagePullSecrets:
        - name: {{.Values.job.imagePullSecrets.name}}
    {{ end }}
      containers:
        - name: {{ .Values.job.name }}
          image: {{ .Values.app.container.image }}
          env:
            - name: CONFIGURATION_SERVER_ENABLED
              value: {{ .Values.job.config.server_enabled | quote}}
            - name: SECRET
              value: {{ .Values.job.config.secret | quote}}
            - name: CLIENT
              value: {{ .Values.job.config.client | quote}}
            - name: POD
              value: {{ .Values.job.config.pod | quote}}
            - name: APPLICATION
              value: "loconav-developer-apis"
          args:
          {{- range .Values.job.container.args }}
            - {{ . }}
          {{- end }}
          imagePullPolicy: {{ .Values.job.container.imagePullPolicy }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: {{ .Values.job.restartPolicy }}
  backoffLimit: 1
